name: APPTX Monitor

on:
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Infinite monitor
        run: |

          while true
          do

            echo "🚀 CHECK $(date)"

            code=$(curl -o /dev/null -s -w "%{http_code}" https://wws.apptx.xyz)

            echo "HTTP CODE: $code"

            if [ "$code" != "200" ]; then

              echo "🔴 SERVER DOWN"

              curl -X POST https://zalo-webhook-u0bm.onrender.com/alert \
              -H "Content-Type: application/json" \
              -d '{"alertTypeFriendlyName":"Down"}'

            else

              echo "🟢 SERVER OK"

            fi

            sleep 30

          done
